const types = {
    GET_CONTACTS: 'GET_CONTACTS',
    DELETE_CONTACT: 'DELETE_CONTACT',
    ADD_CONTACT: 'ADD_CONTACT',
    GET_CONTACT: 'GET_CONTACT',
    UPDATE_CONTACT: 'ADD_CONTACT'
};

export default types;
